### ISSUE TITLE
UnBoundLocalError: local variable 'prefix' referenced before assignment

### ISSUE THREAD

**Issue by NotaKennen** [jakbin/flask-tor#2]
**Describe the bug**
There seems to be a variable "prefix" used somewhere without assigning it first. No idea where.

**How to reproduce**
I ran the "tutorial code", VSCode raises an error on "port = run_with_tor()", with the mentioned error message.

**Expected behavior**
It should have opened a Tor website, but raised an error.

A picture of the code if it helps anything, shouldn't be any different from the "tutorial code" though:
![image](https://github.com/jakbin/flask-tor/assets/107775226/44d54327-7625-49e0-be0c-4e9a0e297c08)

**Comment by NotaKennen** [comment]
Could this be because of my file order? If so, here is also a picture of that:
![image](https://github.com/jakbin/flask-tor/assets/107775226/71a8d67a-5e83-4be4-8278-3fe12025dcff)

**Comment by jakbin** [comment]
What is your os ? and paste here error log .

**Comment by jakbin** [comment]
@NotaKennen wsl or linux based os , it is not working windows.
