### ISSUE TITLE
Add Support for Persistent Tor Hidden Service Domain Using Private Key

### ISSUE THREAD

**Issue by psg4220** [jakbin/flask-tor#4]
Is there a way to set the private key. So that a user wouldn't generate a new tor domain every single time it restarted?.
Or am I missing something?

**Comment by jakbin** [comment]
@psg4220 I just give up that project because I did not get enough response .

**Comment by jakbin** [comment]
It uses older version of onionshare , if we use latest version of onionshare then we can achieve this .

@psg4220

**Comment by jakbin** [comment]
@psg4220 
now, it is possible. See latest docs and example.
